### PR TITLE
Rework emoji fragment as LinearLayout for ability show its as popupWindow on top of the soft keyboard like WhatsApp

### PR DESCRIPTION
**Pull request by kuFEAR**
Rework emoji fragment as LinearLayout for ability show its as popupWindow on top of the soft keyboard like WhatsApp

### CODE REVIEW

**Comment by daniele-athome** [comment]
Hi @rockerhieu any news on this one? I stopped trying because you said you would implement it soon, but if you need help I'm here :-)

**Comment by rockerhieu** [comment]
Hey @daniele-athome sorry I find myself a bit busy during this time. If you can help me on this, you're more than welcome. Btw, here is the code to make `EmojiconFragment` to work with `DialogFragment`:

```java
 @Override
  public Dialog onCreateDialog(Bundle savedInstanceState) {
    TouchEventInterceptableDialog dialog = new TouchEventInterceptableDialog(getActivity(), android.R.style.Theme_Translucent_NoTitleBar);
    Window window = dialog.getWindow();
    window.setLayout(
        WindowManager.LayoutParams.MATCH_PARENT,
        AppSettings.getInstance().getSoftKeyboardHeight());
    WindowManager.LayoutParams wlp = window.getAttributes();
    wlp.gravity = Gravity.BOTTOM;
    wlp.width = WindowManager.LayoutParams.MATCH_PARENT;
    wlp.horizontalMargin = 0;
    window.setAttributes(wlp);
    window.clearFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND | WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE);
    window.addFlags(WindowManager.LayoutParams.FLAG_ALT_FOCUSABLE_IM
        | WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL
        | WindowManager.LayoutParams.FLAG_WATCH_OUTSIDE_TOUCH);
    dialog.setCanceledOnTouchOutside(true);
    dialog.setTouchEventHandler(this);
    return dialog;
  }
```

**Comment by daniele-athome** [comment]
Thanks @rockerhieu! But, wait... how do I use that? I mean EmojiconsFragment is in fact a fragment: how do I integrate it into a dialog? Don't I have to extract the inner gridview and make it standalone first?

**Comment by rockerhieu** [comment]
@daniele-athome you will need to implement a custom `DialogFragment`, the above code is the overrided `onCreateDialog` method. Then you could use the new dialog fragment as `PopupWindow`.

**Comment by daniele-athome** [comment]
@rockerhieu I've ended up transforming the whole Emojicon library to use plain views instead of fragments. It needs a little more fine tuning and then I can send it to you as a patch. Do you think we could keep the library backwards compatible by embedding a view inside a fragment? So I can merge upstream (that is, with you).

**Comment by rockerhieu** [comment]
@daniele-athome: I think we should keep the library backwards compatible :+1:

**Comment by smer4ik** [comment]
Hi, any news on implementation Emojicon Dialog Fragment?

**Comment by CHRehan** [comment]
@rockerhieu please post the piece of code how to use this above method  Dialog onCreateDialog().
@daniele-athome

**Comment by vanniktech** [comment]
+1, I'm also really interested in this

**Comment by dreambash** [comment]
i think this guy ffigured out a good way to handle with the keyboard :) https://github.com/KyoSherlock/EmojiKeyboard

**Comment by vanniktech** [comment]
You could also give https://github.com/vanniktech/emoji a try

**Comment by rockerhieu** [comment]
This feature should be available in `2.0`. Stay tune.

**Pull request closed without merging**
