### PR TITLE
Added EmojiMultiAutoCompleteTextView

### PR DESCRIPTION
**Pull request by EsteveAguilera**
I need it for a project, and I thought it might be useful for someone else…

### CODE REVIEW

**Comment by rockerhieu** [comment]
Looks good, thanks.

**Comment by EsteveAguilera** [comment]
Thanks for accepting the PR! 
Do you plan to release a new version to maven?

**Comment by rockerhieu** [comment]
@EsteveAguilera I will find a time to do it tomorrow GMT+07 ;-)

**Comment by EsteveAguilera** [comment]
Cool! Thanks!

**Pull request merged**
