### PR TITLE
New iOS 9.1 emojis, emoji modifiers (skintones, etc)

### PR DESCRIPTION
**Pull request by pfives**
Addresses issues #82 and #85.  

I did this:
```
String resourceName = "emoji_" + hexUnicode + "_" + hexFollowUnicode;

int resourceId = context.getResources().getIdentifier(resourceName, "drawable", context.getApplicationContext().getPackageName());
```

for handling emoji modifiers rather than adding (64x5) more elements to a map. I'm not totally sure if this will work everywhere but if it does it seems like we could do *something* like this for all the emojis rather than managing those huge maps since all of the drawables are appropriately named.

### CODE REVIEW

**Comment by daniele-athome** [comment]
I think the reason for using the hash map is because Google discourages use of `getIdentifier` because of performance reasons (I'm guessing it uses reflection).

> Note: use of this function is discouraged. It is much more efficient to retrieve resources by identifier than by name.

Source: http://developer.android.com/reference/android/content/res/Resources.html#getIdentifier%28java.lang.String,%20java.lang.String,%20java.lang.String%29

**Comment by pfives** [comment]
Hm yea makes sense. Seems like using actual reflection is way faster (5x) than using getIdentifier()

http://daniel-codes.blogspot.com/2009/12/dynamically-retrieving-resources-in.html

Still not as fast as the map but probably a negligible difference. And significantly easier to maintain.

**Comment by rockerhieu** [comment]
I like your solution, it's clean, and easier to maintain. But given the library already had a poor performance when rendering a lot of emoji at a time, I think we should not make it slower. How about this:
    * Try to use reflection as described in the above link.
    * Use a map as the cache layer

The first time an emoji is rendered, it will take a little more time, but it should be fast from the second time. What do you guys think?

**Comment by pfives** [comment]
Sure that seems reasonable. 
Just to clarify for the cache layer: I'm envisioning a separate map for each skin tone so we can be somewhat consistent and use a single int as the key, this just won't scale well if we have any other types of modifiers (or more than 1 modifier). Alternatively we could convert the full hex to a string or something and use that as a key. Not a big deal but preference?

**Comment by pfives** [comment]
So after digging into this it seems like the pure reflection method is faster because you only have to do 1 reflection lookup whereas `getIdentifier` does 2: one to find the drawable class and one to find the resource. Unfortunately since this is in a library we need to do that lookup anyways (and I couldn't find a consistent way to do it from the library project). `getIdentifier` is also more reliable than our own reflection lookup would be since it will stay consistent as the APIs change.
I don't think it's a big difference either way, haven't noticed any performance hits on my lower-end devices.
Also added a cache layer so we only do this lookup once per new emoji encountered.

**Comment by pfives** [comment]
@rockerhieu gentle nudge...how are we feeling about this?

**Comment by rockerhieu** [comment]
Looks good :+1:

**Comment by daniele-athome** [comment]
Thanks! But I think it's missing the new emojis in the UI (I mean they are parsed but they can't be typed in).

**Pull request merged**
