### PR TITLE
update to new library to fix issue #57

### PR DESCRIPTION
**Pull request by pY4x3g**
I hope this fixes the issue.

### CODE REVIEW

**Comment by rockerhieu** [comment]
The jar file shows me that you're using Eclipse/Ant. It's recommended that you use Android Studio/Gradle instead of the traditional Eclipse project format.

**Comment by rockerhieu** [comment]
What is the version of that support library?

**Comment by pY4x3g** [comment]
I copied the file directly from android-sdk, so with Gradle you don't use the sdk anymore?
The copied library is at revision 22.

**Comment by rockerhieu** [comment]
Already updated support library to latest. Let's close this PR.

**Pull request closed without merging**
