### PR TITLE
Improve performance of emojicon views by verifying that follow unicode is a valid emoji modifier

### PR DESCRIPTION
**Pull request by pfives**
@rockerhieu can you check this out and merge if it looks okay? Greatly improves performance, address issues #106 and #111

### CODE REVIEW

**Comment by rockerhieu** [comment]
Hey @pfives thanks for the PR, I will check it today.

**Comment by KushtrimPacaj** [comment]
@pfives @rockerhieu 
Hi. I tried tried this, and it really improves the performance scroll wise.
I'm wondering whether there is a reason that this pull request wasn't merged, is there a downside to this ?

**Comment by pfives** [comment]
@KushtrimPacaj seems like this library is not being maintained anymore. You can grab this commit from my fork https://github.com/pfives/emojicon/commits/master or optionally check out this other library which was built using emojicon as an inspiration: https://github.com/instachat/emoji-library

**Comment by rockerhieu** [comment]
Sorry I lost track of this one.

**Pull request merged**
